In [ ]:
## list 생성

In [12]:
# list 생성 예시
new_list = []
fruits = ['apple', 'banana', 'orange']
mixed_list = [1, 'hello',3.14, True]

In [15]:
# 리스트 슬라이싱
print(fruits[1:3])

['banana', 'orange']


In [16]:
# 항목 추가
fruits.append('grape')
print(fruits)

['apple', 'banana', 'orange', 'grape']


In [17]:
# 항목 제거
fruits.remove('banana')
print(fruits)

['apple', 'orange', 'grape']


In [19]:
# 항목 제거_인덱스
del fruits[0]
print(fruits)

['orange', 'grape']


In [21]:
# List Comprehension
squares = [x**2 for x in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
## dictionary 생성

In [2]:
# 중괄호 사용
my_dict1 = {
    'key1' : 'value1',
    'key2' : 'value2',
    'key3' : 'value3'    
}
my_dict1

{'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}

In [3]:
# dict() 생성자 사용
my_dict2 = dict(key4='value4', key5='value5', key6='value6')
my_dict2

{'key4': 'value4', 'key5': 'value5', 'key6': 'value6'}

In [4]:
# 키-값 쌍의 리스트를 활용
my_dict3 = dict([('key7','value7'), ('key8','value8'), ('key9','value9')])
my_dict3

{'key7': 'value7', 'key8': 'value8', 'key9': 'value9'}

In [5]:
# 두 리스트 및 zip함수 활용
keys = ['key10','key11','key12']
values = ['value10','value11','value12']
my_dict4 = dict(zip(keys, values))
my_dict4

{'key10': 'value10', 'key11': 'value11', 'key12': 'value12'}

In [6]:
# 딕셔너리 컴프리헨션 사용
keys = ['key13','key14','key15']
values = ['value13','value14','value15']
my_dict5 = {key: value for key, value in zip(keys, values)}

In [7]:
# 항목 추가
my_dict1['key16'] = 'value16'
my_dict1

{'key1': 'value1', 'key2': 'value2', 'key3': 'value3', 'key16': 'value16'}

In [8]:
# 항목 수정
my_dict1['key2'] = 'value17'
my_dict1

{'key1': 'value1', 'key2': 'value17', 'key3': 'value3', 'key16': 'value16'}

In [11]:
# 항목 제거
del my_dict1['key1']
my_dict1

{'key2': 'value17', 'key3': 'value3', 'key16': 'value16'}

In [ ]:
## tuple 생성

In [24]:
# 빈 튜플 생성
empty_tuple = ()

# 요소가 하나인 튜플 생성
tuple_1 = (1,)  # 콤마가 필요합니다.

# 요소가 여러 개인 튜프 생성
tuple_2 = (1, 2, 3, 4)

# 괄호 없이 튜플 생성(패킹)
tuple_3 = 1, 2, 3, 4

In [30]:
# 튜플 사용예 : 함수 여러값 반환시
def divide_and_remainder(a, b):
    quotient = a // b
    remainder = a % b
    return quotient, remainder

print(divide_and_remainder(10,3))

(3, 1)


In [ ]:
## set 생성 ... 집합을 쉽게 처리하기 위한 자료형

In [47]:
# set 생성 예시
set1 = set([1, 2, 3])
set1

{1, 2, 3}

In [37]:
# 중복 허용하지 않고, 순서가 없음
set2 = set('hello')
set2

{'e', 'h', 'l', 'o'}

In [42]:
# 집합 연산
set3 = set([1, 2, 3, 4, 5])
set4 = set([1, 3, 5, 7, 9])
print(set3.intersection(set4))  # 교집합
print(set3.union(set4))  # 합집합
print(set3 - set4)  # 차집합

{1, 3, 5}
{1, 2, 3, 4, 5, 7, 9}
{2, 4}


In [48]:
# 항목 추가
set1.add(11)
print(set1)  # 왜 11이 맨 앞으로 간거지?

{11, 1, 2, 3}


In [49]:
# 항목 여러개 추가
set1.update([21,22,23])
print(set1)

{1, 2, 3, 11, 21, 22, 23}


In [51]:
# 항목 제거
set1.remove(1)
print(set1)

{2, 3, 11, 21, 22, 23}


In [ ]:
## DataFrame 생성

In [53]:
import pandas as pd
df1 = pd.DataFrame()  # 빈 데이터프레임 생성
df1

Empty DataFrame
Columns: []
Index: []

In [59]:
data = {'국어' : [95,88,77,89,90],
       '영어' : [78,66,59,90,89],
       '수학' : [55,78,95,100,69]}
idx = ['김지수', '나혜미','박민영','주현영','홍설아']
df2 = pd.DataFrame(data, index = idx)
df2

국어  영어   수학
김지수  95  78   55
나혜미  88  66   78
박민영  77  59   95
주현영  89  90  100
홍설아  90  89   69

dict

In [ ]:
## numpy 객체 생성 ... .다차원 배열, 행렬을 고속으로 처리하기 위한 자료형

In [62]:
import numpy as np
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [64]:
print(arr1)

[1 2 3]


In [66]:
arr2 = np.array([[3,2], [1,8], [7,6], [5,4]])
print(arr2)

[[3 2]
 [1 8]
 [7 6]
 [5 4]]


In [ ]:
# DataFrame과 numpy는 각각 별도로 정리