In [1]:
import numpy as np
import random

In [2]:
# random() : 0과 1 사이의 무작위 실수를 반환
random.random()

0.7301196767334166

In [3]:
# 숫자 여러개 뽑아서 리스트로 만들때는 list comprehension 활용
[random.random() for i in range(5)]

[0.7338066402088247,
 0.4182614684163264,
 0.5897765226071403,
 0.346288439238583,
 0.6142432943985213]

In [4]:
# uniform(a, b) : a~b 사이의 무작위 실수를 반환
random.uniform(10, 20)

13.352341768523036

In [5]:
# randint(a, b) : a, b 사이의 무작위 정수를 반환
random.randint(10, 20)

20

In [6]:
# randrange(b) : 0, b 사이 무작위 정수를 반환, b는 포함하지 않음
# randrange(a, b) : a, b 사이 무작위 정수를 반환, b는 포함하지 않음
random.randrange(10, 20)

12

In [7]:
# randrange(a, b, step) : a, b 사이 step 만큼 건너뛴 값 중 무작위 정수를 반환, b는 포함하지 않음
random.randrange(1, 9, 2)  # 1, 3, 5, 7 중 임의로 반환

3

In [8]:
# choice(seq) : 시퀀스(문자열, 튜플, range, list) 내 무작위 원소를 뽑음
random.choice('RandomTest')

'n'

In [9]:
# random.sample(seq or set, N) : 시퀀스 내 무작위 원소 N개를 unique하게 뽑아 리스트로 반환
random.sample('RandomTest', 3)

['n', 'T', 'd']

In [10]:
# random.shuffle(seq) : 데이터 순서를 무작위로 변경, 리스트만 가능, 값을 반환하지 않음
a = [*range(10)]
random.shuffle(a)
a

[5, 1, 4, 9, 0, 3, 7, 8, 6, 2]

In [11]:
# seed() : 샘플링 결과가 실행할 때마다 고정된 값을 얻음
random.seed(15)
print([random.randint(0,10) for i in range(5)])

random.seed(15)
print([random.randint(0,10) for i in range(10)])

[3, 0, 8, 0, 2]
[3, 0, 8, 0, 2, 3, 0, 0, 10, 2]


### numpy 난수 생성
값 여러개를 원하는 dimension으로 추출하며, 정규분포 추출이 가능하고, 추출값 연산시 array 연산과 연계 가능

In [12]:
# rand() : 0과 1 사이의 무작위 실수를 반환
np.random.rand()

0.37974704313844976

In [13]:
# rand(n) : 0과 1사이의 무작위 실수를 n개 가지는 넘파이 array 반환
np.random.rand(5)

array([0.09359651, 0.96314056, 0.4546596 , 0.30530269, 0.8880205 ])

In [14]:
# rand(m, n) : 해당 dimension을 가진 넘파이 array 반환
np.random.rand(3,4)

array([[0.34695056, 0.49124855, 0.12738533, 0.85338854],
       [0.60535142, 0.7577996 , 0.86115227, 0.99073927],
       [0.19497918, 0.28885825, 0.22525296, 0.9035021 ]])

In [15]:
# random((m, n)) : 튜플 형태로 입력, 결과는 위와 동일
np.random.random((3,4))

array([[0.32679584, 0.78504753, 0.85376875, 0.81135979],
       [0.86150529, 0.59898627, 0.71908199, 0.82892056],
       [0.29559605, 0.62378318, 0.13029767, 0.00455786]])

In [16]:
# randn() : 표준정규분포를 따르는 무작위 실수를 반환
np.random.randn()

-0.3332444192802298

In [17]:
# randint(a, b, size) : a, b 사이의 무작위 정수를 size개 가지는 넘파이 array 반환, b는 포함하지 않음
np.random.randint(1, 11, size=10)

array([10,  2,  3,  9,  4,  9,  9,  7,  5,  8])

In [18]:
# size에 dimension 입력 가능
np.random.randint(1, 5, (3,4))

array([[4, 4, 1, 4],
       [2, 1, 3, 4],
       [2, 4, 3, 1]])

In [19]:
# choice() : 원하는 조건 하에서 샘플링하기
np.random.choice(
    10,  # 0~해당 숫자-1 범위에서 정수 sampling
    5,   # 추출 개수, 생략시 1
    replace = True  # 복원 추출 여부, *True | False
)

array([9, 2, 6, 8, 2])

In [20]:
np.random.choice(
    ['good', 'excellent', 'bad', 'poor'],  # 리스트 내 원소 sampling
    5,   
    replace = True,
    p = [0.6, 0.2, 0.15, 0.05]  # 각 항목별 추출 확률, 모든 확률의 합은 1이 되어야 함, 생략시 모든 원소 추출 확률 균등
)

array(['good', 'good', 'good', 'good', 'good'], dtype='<U9')

In [21]:
# seed() : 샘플링 결과가 실행할 때마다 고정된 값을 얻음
# np.random 추출 결과 고정시 np.random.seed(n) 사용해야 함. ramdom.seed(n)은 적용되지 않음
np.random.seed(10)
print(np.random.rand(5))
np.random.seed(10)
print(np.random.rand(7))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286]
